### ISSUE TITLE
Canable at 1mbps gives CRC errors

### ISSUE THREAD

**Issue by dan-swartz** [candle-usb/candleLight_fw#10]
I noticed a constant issue with the canable when using it at 1mbps giving constant CRC errors. I'm not sure if its due to the lack of an oscillator or an issue with the clock frequency. Just wanted to let you know. I tested an MCP2515 based interface and had no problems.

**Comment by normaldotcom** [comment]
Interesting... are you getting error frames on the bus?

**Comment by fenugrec** [comment]
Is this still a problem on current master ?
Issue with the clock doesn't seem likely, since the F042 / F072 do clock-recovery on the USB frames and should be more accurate than the usual HSI osc.

**Comment by fenugrec** [comment]
Closing due to staleness. Feel free to reopen or file a new issue as required.
