### ISSUE TITLE
Wronge Controller in Makefile

### ISSUE THREAD

**Issue by Scytie** [candle-usb/candleLight_fw#14]
Currently it is:

```
candleLight:
        $(MAKE) CHIP=STM32F042x6 BOARD=candleLight bin

flash-candleLight:
        $(MAKE) CHIP=STM32F042x6 BOARD=candleLight board-flash

cantact:
        $(MAKE) CHIP=STM32F072xB BOARD=cantact bin

flash-cantact:
        $(MAKE) CHIP=STM32F072xB BOARD=cantact board-flash

```
but it has to be vice versa. Cantact uses F042 and candelight uses F072.

**Comment by fenugrec** [comment]
This seems true. I have neither hardware to test though, @HubertD  can you confirm this ?
If so, I can quickly patch the Makefile and eventually CMakeLists.txt also.

**Comment by HubertD** [comment]
can confirm at least for the candleLight.
At least the one I've got here has a STM32F072.

**Comment by HubertD** [comment]
fixed in current master
