### ISSUE TITLE
startup.c is broken - hardfault with large BSS

### ISSUE THREAD

**Issue by fenugrec** [candle-usb/candleLight_fw#140]
see description in  https://github.com/candle-usb/candleLight_fw/pull/135#issuecomment-1317912852

**Comment by fenugrec** [comment]
incidentally, looking at disasm for good build, there's already a `_start` function that initializes BSS (__bss_start__ to __bss_end__) with `memset`. Still looking into what part of newlib-nano would handle initialized data - I think we have redundancy in startup.c that we could get rid of.

**Comment by marckleinebudde** [comment]
I think the problem is the too large `data` section. See https://github.com/candle-usb/candleLight_fw/pull/141 for a fix.

**Comment by fenugrec** [comment]
Fixed in 59896b65fdd588fed40cc4d9efec00d21f04ad31 via #141 . We still need to initialized .rodata because newlib will not do that for us (it does clear BSS though)

**Comment by marckleinebudde** [comment]
`.rodata` is read only data, right? Does it live in the ROM?

**Comment by fenugrec** [comment]
> `.rodata` is read only data, right? Does it live in the ROM?

my bad, I meant the initialized RAM stuff, `.data`

**Comment by marckleinebudde** [comment]
My patch replaced the 32-bit manual copy loop by a `memcpy()`, which takes length in bytes.

**Comment by fenugrec** [comment]
>So everything should be fine?

Yes. We can't get rid of startup.c , but it should work now.

**Comment by marckleinebudde** [comment]
FYI: https://github.com/ARM-software/CMSIS_5/issues/632
