### ISSUE TITLE
Openmoko firmware upgrade , no jumper to enter DFU mode or button

### ISSUE THREAD

**Issue by pergolafabio** [candle-usb/candleLight_fw#169]
Hi,

hope someone can help me, i have purchased an canable, seems its an Openmoko, i want to change firmware on it, was testing it like below, but it gives errors?
As you can see in screenshot, i dont have a jumper to enter DFU mode? nor do i have a button on it? Anyone seen this before?

![image](https://github.com/candle-usb/candleLight_fw/assets/43251136/a037deac-4c1f-4a32-aa45-d7592a908881)

![image](https://github.com/candle-usb/candleLight_fw/assets/43251136/4d84bb32-a96b-40b6-9f98-85632633115c)

**Comment by marckleinebudde** [comment]
Use `make flash-candleLight_fw` to flash the firmware.

**Comment by pergolafabio** [comment]
hi, thnx for answering, here is the output : 

```
debian@debian:~$ lsusb|grep -i open
Bus 002 Device 004: ID 1d50:606f OpenMoko, Inc. Geschwister Schneider CAN adapter
```

**Comment by marckleinebudde** [comment]
> hi, thnx for answering, here is the output :
> 
> ```
> debian@debian:~$ lsusb|grep -i open
> Bus 002 Device 004: ID 1d50:606f OpenMoko, Inc. Geschwister Schneider CAN adapter
> ```

looks good!

**Comment by marckleinebudde** [comment]
If it's a canable device better flash the canable firmware: `make flash-canable_fw`.

**Comment by pergolafabio** [comment]
sorry, indeed new to this, but according to canable site, i also need to set the jumper or press the button, but i dont see any of those?

**Comment by marckleinebudde** [comment]
It should work without an extra jumper.

**Comment by pergolafabio** [comment]
ah ok, just unclear how to flash? i have downloaded the canable_fw file, as you can see? but the command gives an error?

![image](https://github.com/candle-usb/candleLight_fw/assets/43251136/786bb259-536f-4c75-8a0a-9bfbeeda82af)

**Comment by codebuk** [comment]
I have a sample here of that board. It has a pair of BOOT0 pins labelled on
the rear. I have not reflashed this unit.

[image: image.png]

**Comment by pergolafabio** [comment]
hmm, dont see your image

**Comment by marckleinebudde** [comment]
try `dfu-util -a 0 -R -s 0x08000000 -D canable_fw.dfu`

**Comment by codebuk** [comment]
![image](https://github.com/candle-usb/candleLight_fw/assets/202906/3a5a549b-f059-4bbe-a371-a447a104d122)

**Comment by pergolafabio** [comment]
yeah, mine looks the same indeed, it just named 303canable3 instead

i need to shortwire those pins then ? buts its a plastic box :-)

**Comment by marckleinebudde** [comment]
open the plastic box, or use a solder iron to make some holes :)

**Comment by pergolafabio** [comment]
omg, why did they  make it so difficult then

**Comment by marckleinebudde** [comment]
Use some metal tweezers or unfold a paper clip.

**Comment by pergolafabio** [comment]
just last question, if i use a tweezer or clip, do i need to connect it the while time?
Or is is enough to use the tweezer, then plugin usb , at that point , can i detach the tweezer?
