### ISSUE TITLE
meaning of PRIMASK in the enable/disable irq logic is reversed

### ISSUE THREAD

**Issue by ndushman** [candle-usb/candleLight_fw#17]
The meaning of primask in the enable/disable irq logic in util.c is backwards. Primask is 1 when IRQs are disable, and 0 when they are enabled. The enable_irq function in util.c enables interrupts when primask is 1, and leaves them disabled when 0. As a result, every queue operation toggles whether interrupts are enabled. The code works since there are so many queue operations, but interrupts are only enabled for about half the time they should be.

**Comment by jhofstee** [comment]
https://github.com/candle-usb/candleLight_fw/commit/35b409bf1ef2591065edc0348e2d0f7f453e10b6 closes this..

**Comment by HubertD** [comment]
thanks again for bringing this up!
