### ISSUE TITLE
About candlelight and Cangaroo

### ISSUE THREAD

**Issue by luyang14** [candle-usb/candleLight_fw#170]
I use the Candlelight firmware for USB to CAN conversion and the Cangaroo software on Windows 10, but Cangaroo cannot find the CAN tool.
![image](https://github.com/candle-usb/candleLight_fw/assets/9926722/6c0ba2f9-1f07-4b96-b0ca-33b74da9b668)
![image](https://github.com/candle-usb/candleLight_fw/assets/9926722/3e03cf84-5dbf-40c9-8dd3-22940450d896)
![image](https://github.com/candle-usb/candleLight_fw/assets/9926722/231d60c1-e1d7-43b2-a7bb-84cb3b40799a)

**Comment by fenugrec** [comment]
you should probably file an issue with cangaroo, as this tracker is for the firmware itself. We usually test the firmware with the built-in linux drivers. If you can reproduce your issue on linux however, feel free to reopen.

**Comment by luyang14** [comment]
OK,thanks
