### ISSUE TITLE
Problem ACK on tx error

### ISSUE THREAD

**Issue by v0nHoFF** [candle-usb/candleLight_fw#179]
Hi everyone! I try to configure the candlelight-FD on ubuntu 22.04 with 6.5.0-26-generic kernel and I still get the error no-acknowledgement-on-tx when I'm using the command to configure the interface from the original website (sudo ip link set can0 up type can bitrate 200000 dbitrate 2000000 fd on).

v0nhoff@v0nhoff-706M:~$ sudo ifconfig can0 down
v0nhoff@v0nhoff-706M:~$ sudo ip link set can0 up type can bitrate 200000 dbitrate 2000000 fd on
v0nhoff@v0nhoff-706M:~$ candump any,0:0,#FFFFFFFF -extA
 (2024-03-27 18:33:23.550731)  can0  TX - -  7DF   [2]  01 00
 (2024-03-27 18:33:23.551031)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.551454)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.551861)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.552270)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.552678)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.553796)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.553811)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}
 (2024-03-27 18:33:23.553894)  can0  RX - -  20000020   [8]  00 00 00 00 00 00 88 7F   ERRORFRAME
	no-acknowledgement-on-tx
	error-counter-tx-rx{{136}{127}}

The 7DF#0100 is the message that I've sent using the cansend program in order to start the communication between the car OBD port and candleLight-FD.

**Comment by marckleinebudde** [comment]
If you don't get an ACK, you're effectively alone on the bus or using the wrong bitrate.
