### ISSUE TITLE
CAN able pro flashed with latest version of firmware no windows drivers

### ISSUE THREAD

**Issue by ve3sjk** [candle-usb/candleLight_fw#19]
I recently received 2 new CANable devices and flashed the latest firmware using the webpage app on the canable website. The firmware flashes without error but when re insert the devices i get two usb devices under win7 without drivers. The first is gs usb and the 2nd is a programming port. Win7 reports that no drivers are installed and cangroo does not see any devices.

**Comment by normaldotcom** [comment]
Did you attempt to restart Cangaroo after plugging in the device? The two devices that show up are correct; however, they should use the native WinUSB driver with no extra legwork.

**Comment by fenugrec** [comment]
Closing this until more information or more questions are added. Feel free to reopen.
