### ISSUE TITLE
CANAlyze support

### ISSUE THREAD

**Issue by brandonros** [candle-usb/candleLight_fw#30]
Does this work with https://kkuchera.github.io/canalyze/?

**Comment by fenugrec** [comment]
Maybe, but only if it uses the same pin assignments as other F042-based hardware that is already supported here. You would have to check the schematics, and verify against
https://github.com/candle-usb/candleLight_fw/blob/master/include/config.h for the LED pins and
https://github.com/candle-usb/candleLight_fw/blob/master/src/can.c#L29  for the CAN pins.

**Comment by HubertD** [comment]
CAN is on PB8/PB9 and LEDs are on PB0/PB1.
Looks like canalyze should be compatible with the cantact, which is supported by our firmware.

**Comment by brandonros** [comment]
> Looks like canalyze should be compatible with the cantact, which is supported by our firmware.

For super mega clarity, does this mean that if I put CANAlyze in DFU mode, flash candlight-fw, it would be work out of the box with no changes?

**Comment by HubertD** [comment]
won't give you a guarantee, but I think so.
use the cantact flavor.

would be glad to hear about the outcome.

**Comment by brandonros** [comment]
I will test right now and if it works, I will make a PR to update the README that CANAlyze is supported

Question:

![Uploading image.png…]()

**Comment by brandonros** [comment]
More recent firmware for other people: https://github.com/candle-usb/candleLight_fw/issues/32#issuecomment-552128111

**Comment by fenugrec** [comment]
Yes, we could / should tag a new release. Starting a new issue for that.

**Comment by brandonros** [comment]
> CAN is on PB8/PB9 and LEDs are on PB0/PB1.
> Looks like canalyze should be compatible with the cantact, which is supported by our firmware.

@fenugrec can you double check I got the LED pins right first?
