### ISSUE TITLE
STM32F407VG support

### ISSUE THREAD

**Issue by brandonros** [candle-usb/candleLight_fw#49]
I bought stm32f4discovery + SN65HVD230

what do I need to change in this repo to compile this firmware for this device to make it support the `STM32F407VG` chip?

**Comment by fenugrec** [comment]
- make sure libopencm3 provides functional USB and CAN support for that device
- configure clocks (RCC), and add a device type for the pin assignments
- troubleshoot other issues I haven't foreseen

**Comment by brandonros** [comment]
> configure clocks (RCC), and add a device type for the pin assignments

can you link what file(s) in this repo that would be under?

**Comment by fenugrec** [comment]
We have at least some F407 support since d3067989233e9be383c0179ffd5acdcc605ec9bc .
