### ISSUE TITLE
Candle.NET : a Windows .NET wrapper for candle communications

### ISSUE THREAD

**Issue by elliotwoods** [candle-usb/candleLight_fw#57]
I'm not sure where the best place is to list this 
but I made a .NET wrapper for the candle API on windows:
https://github.com/elliotwoods/Candle.NET

**Comment by fenugrec** [comment]
Cool, thanks for sharing. I guess I could add some links to the README

**Comment by fenugrec** [comment]
merged in d2cb159

**Comment by elliotwoods** [comment]
Thank you!
