### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by riodda** [candle-usb/candleLight_fw#9]
I'm using the same toolchain i use to build canable firmware, trying to make BOARD=all i have the error:

arm-none-eabi-gcc: error: nano.specs: No suche file of directory

**Comment by jhofstee** [comment]
This sounds like a toolchain issue (newlib to be more specific). Since this is a old issue can this be closed or is this still relevant?

**Comment by fenugrec** [comment]
Not sure if this still valid, feel free to reopen. You are probably missing the arm-none-eabi-newlib package on your distro.
